// Generated by IB v0.6.0 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import <UIKit/UIKit.h>
#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>

@interface AppDelegate: UIResponder <UIApplicationDelegate>
@end

@interface MainController: UIViewController

@property IBOutlet UILabel * answerView;

-(IBAction) viewDidLoad;
-(IBAction) findAnswer;

@end

